In [4]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

#Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\HomePC\.conda\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [5]:
df[pd.notna(df['salary_year_avg'])]['salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [6]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [7]:
df_salary = df[pd.notna(df['salary_year_avg'])]

def projected_salary(salary):
    return salary * 1.05

df_salary['salary_year_inflated'] =df_salary['salary_year_avg'].apply(projected_salary)

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             114975.00
77             140000.0             147000.00
92             120000.0             126000.00
100            228222.0             239633.10
109             89000.0              93450.00
...                 ...                   ...
785624         139216.0             146176.80
785641         150000.0             157500.00
785648         221875.0             232968.75
785682         157500.0             165375.00
785692         157500.0             165375.00

[22003 rows x 2 columns]

In [8]:
df_salary = df[pd.notna(df['salary_year_avg'])].copy()

def projected_salary(salary):
    return salary * 1.05

df_salary['salary_year_inflated'] =df_salary['salary_year_avg'].apply(projected_salary)

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             114975.00
77             140000.0             147000.00
92             120000.0             126000.00
100            228222.0             239633.10
109             89000.0              93450.00
...                 ...                   ...
785624         139216.0             146176.80
785641         150000.0             157500.00
785648         221875.0             232968.75
785682         157500.0             165375.00
785692         157500.0             165375.00

[22003 rows x 2 columns]

In [9]:
df_salary = df[pd.notna(df['salary_year_avg'])].copy()

# Function to increase salary by 5%
def projected_salary(salary):
    return salary * 1.05

# Create new column
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(projected_salary)

# Display selected columns
df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             114975.00
77             140000.0             147000.00
92             120000.0             126000.00
100            228222.0             239633.10
109             89000.0              93450.00
...                 ...                   ...
785624         139216.0             146176.80
785641         150000.0             157500.00
785648         221875.0             232968.75
785682         157500.0             165375.00
785692         157500.0             165375.00

[22003 rows x 2 columns]

In [10]:
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(lambda x: x * 1.05)

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             114975.00
77             140000.0             147000.00
92             120000.0             126000.00
100            228222.0             239633.10
109             89000.0              93450.00
...                 ...                   ...
785624         139216.0             146176.80
785641         150000.0             157500.00
785648         221875.0             232968.75
785682         157500.0             165375.00
785692         157500.0             165375.00

[22003 rows x 2 columns]

In [11]:
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'] *1.05

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             114975.00
77             140000.0             147000.00
92             120000.0             126000.00
100            228222.0             239633.10
109             89000.0              93450.00
...                 ...                   ...
785624         139216.0             146176.80
785641         150000.0             157500.00
785648         221875.0             232968.75
785682         157500.0             165375.00
785692         157500.0             165375.00

[22003 rows x 2 columns]

In [12]:
type(df['job_skills'][0]    )

float

In [29]:
df['job_skills'] = df['job_skills'].astype('string')

In [30]:
df['job_skills'].dtype

In [31]:
type(df['job_skills'][0])

pandas.api.typing.NAType

import ast

type(ast.literal_eval(df['job_skills'][0]))

In [33]:
import ast

type(ast.literal_eval(df['job_skills'][0]))

ValueError: malformed node or string: <NA>

In [34]:
import ast
import pandas as pd

# Remove null values first
df_skills = df[pd.notna(df['job_skills'])].copy()

# Convert string lists into actual lists
df_skills['job_skills'] = df_skills['job_skills'].apply(ast.literal_eval)

df_skills['job_skills']

1                [r, python, sql, nosql, power bi, tableau]
2         [python, sql, c#, azure, airflow, dax, docker,...
3         [python, c++, java, matlab, aws, tensorflow, k...
4         [bash, python, oracle, aws, ansible, puppet, j...
5                                        [python, sql, gcp]
                                ...
785736    [bash, python, perl, linux, unix, kubernetes, ...
785737                               [sas, sas, sql, excel]
785738                                  [powerpoint, excel]
785739    [python, go, nosql, sql, mongo, shell, mysql, ...
785740                                          [aws, flow]
Name: job_skills, Length: 668704, dtype: object

In [35]:
import ast
import pandas as pd

value = df['job_skills'][0]

if pd.notna(value):
    print(ast.literal_eval(value))

In [37]:
df[pd.isna(df['job_skills'])]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,<NA>,<NA>,NaN
21,Data Scientist,Stage - data scientist – génération ia de donn...,"Asnières-sur-Seine, France",via Jobijoba,Full-time,False,France,2023-02-23 13:41:21,False,False,France,NaN,NaN,NaN,<NA>,<NA>,NaN
26,Data Engineer,Data Engineer,United States,via LinkedIn,Full-time,False,Georgia,2023-09-15 13:56:18,True,False,United States,NaN,NaN,NaN,<NA>,<NA>,NaN
29,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Exusia,Full-time,False,India,2023-03-26 13:16:20,False,False,India,NaN,NaN,NaN,<NA>,<NA>,NaN
36,Data Analyst,Data Analyst,"Des Moines, IA",via Trabajo.org,Full-time,False,"Illinois, United States",2023-11-06 13:01:22,False,True,United States,NaN,NaN,NaN,<NA>,<NA>,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785713,Cloud Engineer,"Data Center Chief Engineer, AWS Infrastructure...","Bangkok, Thailand",melalui LinkedIn,Pekerjaan tetap,False,Thailand,2023-03-12 06:37:47,False,False,Thailand,NaN,NaN,NaN,<NA>,<NA>,NaN
785715,Data Analyst,Amul Careers 2023 - Apply Online - Data Analys...,India,melalui Jobsleworld - Jobs In India - Job Vaca...,Pekerjaan tetap,False,India,2023-03-13 06:16:28,False,False,India,NaN,NaN,NaN,<NA>,<NA>,NaN
785718,Business Analyst,Senior Performance QA Analyst,India,melalui BeBee India,Pekerjaan tetap,False,India,2023-03-13 06:16:28,False,False,India,NaN,NaN,NaN,<NA>,<NA>,NaN
785724,Data Engineer,Junior Consultant Data Engineering,"Koln, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-13 06:19:07,False,False,Germany,NaN,NaN,NaN,<NA>,<NA>,NaN
785729,Data Engineer,Data Engineer Marketing Intelligence,Jerman,melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,<NA>,<NA>,NaN

In [40]:
def clean_list(skill_list):
    if pd.notna(skill_list):
      return ast.literal_eval(skill_list)
    return skill_list
df['job_skills'] = df['job_skills'].apply(clean_list)

In [43]:
type(df['job_skills'][0])

pandas.api.typing.NAType

In [44]:
# See the raw values
df['job_skills'].head(10)

0                                                 <NA>
1           [r, python, sql, nosql, power bi, tableau]
2    [python, sql, c#, azure, airflow, dax, docker,...
3    [python, c++, java, matlab, aws, tensorflow, k...
4    [bash, python, oracle, aws, ansible, puppet, j...
5                                   [python, sql, gcp]
6    [sql, python, java, sql server, gcp, bigquery,...
7    [sql, nosql, gcp, azure, aws, bigquery, databr...
8                        [excel, powerpoint, power bi]
9    [sql, python, r, mongodb, mongodb, sql server,...
Name: job_skills, dtype: object

In [45]:
# Before clean_list
type(df['job_skills'][1])   # <class 'str'>  ← string like "['python', 'sql']"

# After clean_list  
type(df['job_skills'][1])   # should be <class 'list'> ✅

list

In [46]:
import ast  # ✅ must be imported first!
import pandas as pd

def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)
    return skill_list

df['job_skills'] = df['job_skills'].apply(clean_list)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [47]:
# Find first non-null row
df['job_skills'].dropna().iloc[0]        # see the value
type(df['job_skills'].dropna().iloc[0])  # should be <class 'list'> ✅

list

In [49]:
type(df['job_skills'][0])

pandas.api.typing.NAType

In [52]:
df['job_skills'] = df['job_skills'].apply(lambda skill_list: ast.literal_eval(skill_list) if pd.notna(skill_list) else skill_list)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [53]:
# Step 1 - Reload fresh data ✅
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

# Step 2 - Apply clean_list only ONCE ✅
import ast

def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)
    return skill_list

df['job_skills'] = df['job_skills'].apply(clean_list)

# Step 3 - Verify ✅
type(df['job_skills'].dropna().iloc[0])  # should be <class 'list'>

list

In [55]:
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(lambda x: x * 1.05)

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             114975.00
77             140000.0             147000.00
92             120000.0             126000.00
100            228222.0             239633.10
109             89000.0              93450.00
...                 ...                   ...
785624         139216.0             146176.80
785641         150000.0             157500.00
785648         221875.0             232968.75
785682         157500.0             165375.00
785692         157500.0             165375.00

[22003 rows x 2 columns]

In [60]:
def projected_salary(row):
    if "Senior" in row['job_title_short']:
        return 1.05 * row['salary_year_avg'] 
    return row['salary_year_avg']
    else:
    return 1.03 * row['salary_year_avg']

df_salary['salary_year_inflated'] = df_salary.apply(projected_salary, axis=1)

df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']]

SyntaxError: invalid syntax (4048195504.py, line 5)

In [ ]:
def projected_salary(row):
    if "Senior" in row['job_title_short']:
        return 1.05 * row['salary_year_avg']  # Senior gets 5% raise
    else:
        return 1.03 * row['salary_year_avg']  # Everyone else gets 3% raise ✅

df_salary['salary_year_inflated'] = df_salary.apply(projected_salary, axis=1)

df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]

In [63]:
df_salary['salary_year_inflated'] = df_salary.apply()
    lambda row: row['salary_year_avg'] * 1.05 
    if "Senior" in row['job_title_short']
else row['salary_year_avg'] * 1.03,
axis=1)

df_salary['salary_year_inflated'] = df_salary.apply(projected_salary, axis=1)

df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']]

IndentationError: unexpected indent (342927494.py, line 2)

In [64]:
df_salary['salary_year_inflated'] = df_salary.apply(
    lambda row: row['salary_year_avg'] * 1.05 
    if "Senior" in row['job_title_short'] 
    else row['salary_year_avg'] * 1.03, 
    axis=1
)

df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]